### ISSUE TITLE
采取 token 登录方式会导致接口 -500 和 -2017

### ISSUE THREAD

**Issue by xuewl** [fastgoo/ipadchat-api#2]
重现步骤：
1. 用扫码登录正确获取到 wx_data、token 并持久化存储；
2. 用第 1 步存储的 wx_data 与 token 进行 token 登录（短线重链接），这时返回请求登录成功（但回调地址收不到任何有关 push 的信息，包括 login_success 事件也无法接收到）。
3. 若再实例化，采取 token 登录，则会一直提示-500 和 - 2017

------------------
关于登录的建议
账号登录，作为项目/应用保障安全，降低封号风险的重要手段，应严格按照微信设备规则进行交互及校验，也是项目落地的重要环节和因素，毕竟再强大的功能，协议，若无法尽最大可能保障安全，就难以有真正的业务落地。
通过我之前接触的其它类似产品，对登录部分相关的大量实际业务实践，提出以下建议，仅供作者和其它开发者参考：

> 将登录方式按权重优先级顺序设置为： token、request、qrcode

其中，表现形式为：
1. token（短线重链）：就是无需确认，无需扫码，直接登录，相当于在 iPad 上按 home 回到桌面，又点击微信进去，所以无需任何验证。
2. request（二次登录）：无需扫码，需要确认，同意后登录。相当于在 iPad 上登录的设备，被其它设备（如PC，非当前 iPad）挤下线，现在进入微信要手机点击一下同意。
3. qrcode（二维码登录）：这个场景非常多，如果携带了 wx_data 设备参数，则代表这个 iPad 之前被号主在手机端强制下线或在设备管理里删除了。如果没有携带 wx_data ，一般代表第一次在这个 iPad 上登录。

----------------
以上场景仅供参考，注意所有的登录方式都应支持传递 wx_data ，且强列建议非首次登录均传递该值以降低封号风险。

**Comment by fastgoo** [comment]
这里含有登录的策略，目前服务端接口是正常的了
