### ISSUE TITLE
二维码图片希望能得到自动清理

### ISSUE THREAD

**Issue by xuewl** [fastgoo/ipadchat-api#5]
因登录二维码有效期非常短，服务端没有做清除策略。建议：

1、服务器端直接返回二维码的文本，无需生成图片，由客户端自行生成（可避免暴露服务器端地址）
2、生成后服务器检测二维码的扫码状态，进行清理冗余图片。

**Comment by fastgoo** [comment]
已采纳，更新新版看一下。在服务端检测扫码状态来删除二维码图片
